#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6670701663                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Embrk                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Challenge Yourself, Achieve More, Embrk on Greatness

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Ty Mitchell                               
your_link                                 :                     
your_city                                 : Dallas                               
email_address                             : tymitchell100@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Create and Join Challenges
    description                           : Easily create your own challenges or join community-driven ones to achieve your fitness and lifestyle goals.
    fontawesome_icon_name                 : trophy
    
  - title                                 : HealthKit Integration 
    description                           : Automatically track your progress using Apple HealthKit data, including steps, active energy, and more.
    fontawesome_icon_name                 : heartbeat

  - title                                 : Social Motivation
    description                           : Connect with friends, share achievements, and compete on leaderboards to stay motivated.
    fontawesome_icon_name                 : users

  - title                                 : Diverse Challenge Types
    description                           : Choose from fitness, education, lifestyle, and miscellaneous challenges to improve various aspects of your life.
    fontawesome_icon_name                 : layer-group

  
  - title                                 : Progress Tracking(Coming Soon)
    description                           : Visualize your progress with intuitive charts and statistics for each challenge you participate in.
    fontawesome_icon_name                 : chart-line

  - title                                 : Customizable Goals
    description                           : Set personalized goals for each challenge, tailored to your individual needs and abilities.
    fontawesome_icon_name                 : bullseye

  - title                                 : Daily Verification
    description                           : Easily verify your daily progress through various methods, including manual input and automatic HealthKit data.
    fontawesome_icon_name                 : check-circle


  - title                                 : Community Challenges
    description                           : Participate in official app-wide challenges or create your own community challenges.
    fontawesome_icon_name                 : globe

  - title                                 : Privacy Controls
    description                           : Manage your privacy settings and control what information you share with other users.
    fontawesome_icon_name                 : user-shield


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
